apiVersion: v1
kind: Pod
metadata:
  labels:
    run: temp-busybox
  name: temp-busybox
  namespace: default
spec:
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: temp-busybox
    