# this is a comment

#employee:
# - name: bhakti
#   age: 32
#   address: 1.7
# - name: raj
#   age: 33
#   address:
#    - old
#    - new

# This is a sample pod yaml

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: demo
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerPort: 80