apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        env: demo
      name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      env: demo